spring:
  application.name: spring-security

  security:
    filter.order: -100 # Default value

  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init-ddl.sql
      data-locations: classpath:sql/init-dml.sql

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging.level:
  root: info
  org.springframework.security: trace

